spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: fleaMarket
      username: mongoadmin
      password: mypassw0rd
keys:
  jwt:
    secret: "thisismypasswordthisismypasswordthisismypasswordthisismypasswordthisismypassword"
    expiration-time: 864000
  password:
    secret: "mypassword"
    iteration: 32
    key-length: 256
logging:
  level:
    root: info
